#name: staging-deployment
#
#on:
#  push:
#    branches: [ staging ]
#
#jobs:
#  deploy:
#
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Deploy to staging
#        uses: andiLeong/my-e-commence@staging
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          script: whoami



name: staging-deployment

on:
  push:
    branches: [ staging ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to staging
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT }}
          command: whoami


#uses: fifsky/ssh-action@master
#with:
#  command: |
#    cd /tmp
#    ls -a
#  host: ${{ secrets.HOST }}
#  user: root
#  key: ${{ secrets.PRIVATE_KEY}}


#name: staging-deployment
#on: [push]
#jobs:
#  Staging-Deployment:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "üçè This job's status is ${{ job.status }}."
